wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-08
architecture:
  desc: null
  value: 3D CNN
dataset:
  desc: null
  value: KTH
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715668469.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.7
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
